# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('project_text', models.TextField(null=True)),
                ('project_jindu', models.DecimalField(decimal_places=4, max_digits=6)),
                ('is_over', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Today_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_jindu', models.DecimalField(decimal_places=4, max_digits=6)),
                ('now_day', models.DateField(auto_now_add=True)),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user_type', models.IntegerField(choices=[(1, '权限管理人'), (2, '项目经理'), (3, '标注员'), (4, '质检员')])),
                ('user_ico', models.FileField(default='user_ico/01default.jpg', upload_to='user_ico/%Y/')),
                ('is_disabled', models.BooleanField(default=0)),
                ('my_project', models.ManyToManyField(to='app01.Projects')),
            ],
        ),
        migrations.AddField(
            model_name='today_work',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
