# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20201104_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_project',
        ),
        migrations.AddField(
            model_name='projects',
            name='my_project',
            field=models.ManyToManyField(to='app01.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, '最高管理员'), (2, '项目经理'), (3, '标注员'), (4, '质检员')], default=4),
        ),
    ]
