# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201105_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_disabled',
            field=models.BooleanField(default=0),
        ),
    ]
