# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_projects_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='my_project',
            field=models.ManyToManyField(null=True, to='app01.User'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_jindu',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
    ]
