# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20201105_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_jindu',
            field=models.IntegerField(default=0),
        ),
    ]
