# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, '权限管理人'), (2, '项目经理'), (3, '标注员'), (4, '质检员')], default=4),
        ),
    ]
