# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
        ),
    ]
