# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-05 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20201105_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='my_project',
            new_name='to_user',
        ),
    ]
