# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-06 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20201105_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
